language: c
sudo: false
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p $HOME/.local/bin
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack setup
- stack install pandoc
script:
- stack --no-terminal --skip-ghc-check build
after_success:
- stack exec build-workshop
- git -C workshop checkout master
- zip -r git-internals-workshop workshop
- bash .ci/update_pages.sh
deploy:
  provider: releases
  api_key:
    secure: YN4w+d4wiQxrvRJUqPdYYHHksg1WixWHRN5xub4MWhOmAtjRxSFDIeavVk81UlgC9rg7M4w+G561oMuB/wV/AtIprAk4b2BgEiOhm2NUpy+1k2231Yj9v/30O5P1ZaLfDm3celYWAKkkmAVoPY6aYZ7L8xQg957GRb44Crz44EPD6DGKyhIMyCGjpEbhQH9SA6D1AZ5qO+ZLsvKI2nVb4BmgDs5x+QULVcnYGIbFZhhI/InNHVOFKQhRZCH3q+AO4yYqg4T/PDjHT7BPDEqCYg7aeUSdqqIaLVPY3WMjV68l2jqLv9S5KnNPzJ4l+09B2s4ezS4gy3f5VefWEfzq2lX7wRJNzrGSMqcL1v8/QqIZLtnQJbVIBgVNeGrJ0CTJr5hvea7/kAJ69QX4iN/wOwTDrZol4XLPPilabXYH+J5m1MV4bk7Y5AIGcKJfuycpGSi0OhDnYrL+LxdyjGvjweg7F9yh6j1QjW8Jr0reapEtvib07lDAM3rFefVkHwR9Yu9Rp4QeFCbarGyAp6+hJq+KQUhaFwjCaq8Z+zYQiZlBxrLV3OQSEK8OxxccgGeRo9pe3UGR9+ixHhzZlPFTdjnwqtkNqZvaB6Wqd5rnSoGWyYrqqKQ2jJR3RdSa1lmH4F+TBphmcGOcr59M19Af6APA9lPcv1kfz8TvT482REM=
  skip_cleanup: true
  file: git-internals-workshop.zip
  on:
    repo: vaibhavsagar/git-internals-workshop
    all_branches: true
    tags: true
